In [1]:
import numpy as np

In [2]:
# inputs and outputs
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
print(X)
print(Y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [3]:
# sigmoid function
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [5]:
#forward prop without any hidden layer
# 2 inputs, 1 bias, 1 output NN

weights = 2*np.random.random((2,1))-1
print(weights,"\n")

# no hidden layer weights
bias = 2*np.random.random(1)-1
print(bias)

output0 = X
output = sig(np.dot(output0,weights)+bias)
lr = 10
output

[[-0.37275043]
 [-0.24088332]] 

[0.10200194]


array([[0.5254784 ],
       [0.46533535],
       [0.43272335],
       [0.37481107]])

In [6]:
#calculating error derivative and updating weights and biases
for iter in range(1000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)
    
    first_term = output-Y 
    input_for_last_layer = np.dot(output0,weights)+bias  #inputj
    second_term = derivativeSig(input_for_last_layer)
    prod = first_term*second_term

    
#     slope = np.array([[0.0],[0.0]])

#     for i in range(2):
#         for j in range(4):
#             slope[i][0] += prod[j][0]*output0[j][i]

#     weights = weights-lr*slope
#     bias_change = 0.0
    
#     for j in range(4):
#             bias_change += prod[j][0]*1
#     bias = bias - lr*bias_change


    slope = np.dot(output0.T,prod)
    weights = weights-lr*slope
    bias_change = np.sum(prod)
    bias = bias-lr*bias_change
    
output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[8.03700207],
        [8.03700207]]),
 array([-12.14194766]),
 array([[5.33109984e-06],
        [1.62233778e-02],
        [1.62233778e-02],
        [9.80773584e-01]]))

# XOR NN

In [7]:
# inputs and outputs
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
print(X)
print(Y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [25]:
# NN with 2 inp neuron, 2hidden neuron,1output
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1
lr = 0.1

In [29]:
for itr in range(10000):
    output0 = X
    inputHidden = np.dot(output0,wh)+bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,wo)+bo
    output = sig(inputForOutputLayer)

    first_term_output_layer = output-Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    slope_output = np.dot(outputHidden.T,first_two_output_layer)
    slope_output_bias = np.sum(first_two_output_layer,axis = 0,keepdims = True)

    slope_hidden = np.dot(output0.T,first_two_hidden_layer)
    slope_hidden_bias = np.sum(first_two_hidden_layer,axis = 0,keepdims = True)

    wo = wo-lr*slope_output
    bo = bo-lr*slope_output_bias

    wh = wh-lr*slope_hidden
    bh = bh-lr*slope_hidden_bias
    
output0 = X
inputHidden = np.dot(output0,wh)+bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden,wo)+bo
output = sig(inputForOutputLayer)
output, wh, bh, wo, bo

(array([[0.01766855],
        [0.98142999],
        [0.98142819],
        [0.02287782]]),
 array([[-4.8753944 , -6.04921417],
        [-4.87579688, -6.05076915]]),
 array([[7.26508873, 2.44447736]]),
 array([[ 9.51048959],
        [-9.8215885 ]]),
 array([[-4.4845837]]))